// Per-race wind climatology — the realistic seasonal baseline each race's wind
// field is seeded from. GENERATED by `node scripts/build-weather.mjs`; do not
// hand-edit. With network access the script pulls real wind statistics from
// Open-Meteo for each course's waters in its racing season; offline it falls
// back to a `seed` baseline derived from the race's prevailing wind, so the app
// and CI never need the network (the same pattern as the coastlines).
//
// The engine reads this in `createWindField`: a present entry refines the
// field's direction, strength, gustiness and directional variability. Ranked
// races stay fully deterministic — this only changes the per-race baseline.

export interface RaceClimate {
  fromDeg: number; // mean wind direction the breeze blows FROM
  speedKn: number; // mean wind speed
  gustFactor: number; // gust/lull spread as a fraction of the mean (0–~0.5)
  variabilityDeg: number; // directional spread; scales the field's oscillating shift
  source: 'open-meteo' | 'seed';
  sampledAt?: string; // ISO date the Open-Meteo snapshot was taken
}

export const WEATHER_CLIMATOLOGY: Record<string, RaceClimate> = {
  'race-caribbean-600': {"fromDeg":75,"speedKn":18,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-chicago-mac': {"fromDeg":200,"speedKn":10,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-fastnet': {"fromDeg":240,"speedKn":18,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-middle-sea': {"fromDeg":315,"speedKn":14,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-newport-bermuda': {"fromDeg":225,"speedKn":15,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-r2ak': {"fromDeg":315,"speedKn":12,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-round-island': {"fromDeg":225,"speedKn":12,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-sydney-hobart': {"fromDeg":30,"speedKn":16,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
  'race-transpac': {"fromDeg":45,"speedKn":16,"gustFactor":0.2,"variabilityDeg":20,"source":"seed"},
};
