// Per-race wind climatology — the realistic seasonal baseline each race's wind
// field is seeded from. GENERATED by `node scripts/build-weather.mjs`; do not
// hand-edit. With network access the script pulls real wind statistics from
// Open-Meteo for each course's waters in its racing season; offline it falls
// back to a `seed` baseline derived from the race's prevailing wind, so the app
// and CI never need the network (the same pattern as the coastlines).
//
// The engine reads this in `createWindField`: a present entry refines the
// field's direction, strength, gustiness and directional variability. Ranked
// races stay fully deterministic — this only changes the per-race baseline.

export interface RaceClimate {
  fromDeg: number; // mean wind direction the breeze blows FROM
  speedKn: number; // mean wind speed
  gustFactor: number; // gust/lull spread as a fraction of the mean (0–~0.5)
  variabilityDeg: number; // directional spread; scales the field's oscillating shift
  source: 'open-meteo' | 'seed';
  sampledAt?: string; // ISO date the Open-Meteo snapshot was taken
}

export const WEATHER_CLIMATOLOGY: Record<string, RaceClimate> = {
  'race-annapolis-newport': {"fromDeg":200.2,"speedKn":11.6,"gustFactor":0.41,"variabilityDeg":64.6,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-antigua-360': {"fromDeg":101.4,"speedKn":8.8,"gustFactor":0.35,"variabilityDeg":50.3,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-bayview-mac': {"fromDeg":200.9,"speedKn":5.3,"gustFactor":0.42,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-block-island': {"fromDeg":148.1,"speedKn":9.5,"gustFactor":0.46,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cabbage-tree': {"fromDeg":59.6,"speedKn":13.4,"gustFactor":0.41,"variabilityDeg":62.5,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cape2rio': {"fromDeg":68.2,"speedKn":9.9,"gustFactor":0.52,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-caribbean-600': {"fromDeg":97.4,"speedKn":12,"gustFactor":0.33,"variabilityDeg":53.6,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-chicago-mac': {"fromDeg":253.1,"speedKn":7,"gustFactor":0.41,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-china-sea': {"fromDeg":129.1,"speedKn":8.6,"gustFactor":0.5,"variabilityDeg":65,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-day1': {"fromDeg":244.6,"speedKn":10.2,"gustFactor":0.47,"variabilityDeg":57.3,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-day2': {"fromDeg":243.3,"speedKn":9.5,"gustFactor":0.49,"variabilityDeg":56.7,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-day3': {"fromDeg":244.6,"speedKn":10.2,"gustFactor":0.47,"variabilityDeg":57.3,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-day4': {"fromDeg":244.9,"speedKn":8.9,"gustFactor":0.47,"variabilityDeg":59.8,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-day5': {"fromDeg":244.6,"speedKn":10.2,"gustFactor":0.47,"variabilityDeg":57.3,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-cowes-dinard': {"fromDeg":252.5,"speedKn":12,"gustFactor":0.45,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-ensenada': {"fromDeg":278.2,"speedKn":7.2,"gustFactor":0.59,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-faerder': {"fromDeg":193.5,"speedKn":7.1,"gustFactor":0.53,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-fastnet': {"fromDeg":259.2,"speedKn":11.3,"gustFactor":0.47,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-giraglia': {"fromDeg":210,"speedKn":10.2,"gustFactor":0.49,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-islands-race': {"fromDeg":266.2,"speedKn":9.5,"gustFactor":0.6,"variabilityDeg":66.5,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-malta-syracuse': {"fromDeg":258.2,"speedKn":8.2,"gustFactor":0.59,"variabilityDeg":62.4,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-marion-bermuda': {"fromDeg":219,"speedKn":10.8,"gustFactor":0.53,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-middle-sea': {"fromDeg":93,"speedKn":9.5,"gustFactor":0.54,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-newport-bermuda': {"fromDeg":226.6,"speedKn":13.1,"gustFactor":0.46,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-r2ak': {"fromDeg":199,"speedKn":3.5,"gustFactor":0.6,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-round-island': {"fromDeg":274.2,"speedKn":8.5,"gustFactor":0.53,"variabilityDeg":67.9,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-swiftsure': {"fromDeg":264.1,"speedKn":6.7,"gustFactor":0.5,"variabilityDeg":50.8,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-sydney-goldcoast': {"fromDeg":259.2,"speedKn":6.1,"gustFactor":0.53,"variabilityDeg":56.8,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-sydney-hobart': {"fromDeg":291.9,"speedKn":16.3,"gustFactor":0.43,"variabilityDeg":67.8,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-transpac': {"fromDeg":40,"speedKn":12.4,"gustFactor":0.36,"variabilityDeg":32.6,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-tri-state': {"fromDeg":74.7,"speedKn":10.5,"gustFactor":0.45,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
  'race-van-isle': {"fromDeg":211.1,"speedKn":3.7,"gustFactor":0.6,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-09-01"},
};
