// Per-race wind climatology — the realistic seasonal baseline each race's wind
// field is seeded from. GENERATED by `node scripts/build-weather.mjs`; do not
// hand-edit. With network access the script pulls real wind statistics from
// Open-Meteo for each course's waters in its racing season; offline it falls
// back to a `seed` baseline derived from the race's prevailing wind, so the app
// and CI never need the network (the same pattern as the coastlines).
//
// The engine reads this in `createWindField`: a present entry refines the
// field's direction, strength, gustiness and directional variability. Ranked
// races stay fully deterministic — this only changes the per-race baseline.

export interface RaceClimate {
  fromDeg: number; // mean wind direction the breeze blows FROM
  speedKn: number; // mean wind speed
  gustFactor: number; // gust/lull spread as a fraction of the mean (0–~0.5)
  variabilityDeg: number; // directional spread; scales the field's oscillating shift
  source: 'open-meteo' | 'seed';
  sampledAt?: string; // ISO date the Open-Meteo snapshot was taken
}

export const WEATHER_CLIMATOLOGY: Record<string, RaceClimate> = {
  'race-annapolis-newport': {"fromDeg":200.2,"speedKn":11.6,"gustFactor":0.41,"variabilityDeg":64.6,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-antigua-360': {"fromDeg":101.4,"speedKn":8.8,"gustFactor":0.35,"variabilityDeg":50.3,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-cabbage-tree': {"fromDeg":59.6,"speedKn":13.4,"gustFactor":0.41,"variabilityDeg":62.5,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-caribbean-600': {"fromDeg":95.2,"speedKn":12.1,"gustFactor":0.33,"variabilityDeg":52.8,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-chicago-mac': {"fromDeg":268,"speedKn":7.2,"gustFactor":0.42,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-cowes-dinard': {"fromDeg":252.5,"speedKn":12,"gustFactor":0.45,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-fastnet': {"fromDeg":251.5,"speedKn":11.9,"gustFactor":0.47,"variabilityDeg":61,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-islands-race': {"fromDeg":266.2,"speedKn":9.5,"gustFactor":0.6,"variabilityDeg":66.5,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-malta-syracuse': {"fromDeg":258.2,"speedKn":8.2,"gustFactor":0.59,"variabilityDeg":62.4,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-middle-sea': {"fromDeg":44.3,"speedKn":9,"gustFactor":0.58,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-newport-bermuda': {"fromDeg":226.6,"speedKn":12.9,"gustFactor":0.46,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-r2ak': {"fromDeg":199.3,"speedKn":3.1,"gustFactor":0.56,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-round-island': {"fromDeg":273.4,"speedKn":8.4,"gustFactor":0.52,"variabilityDeg":67,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-swiftsure': {"fromDeg":264.1,"speedKn":6.7,"gustFactor":0.5,"variabilityDeg":50.8,"source":"open-meteo","sampledAt":"2026-07-04"},
  'race-sydney-hobart': {"fromDeg":286.9,"speedKn":16.1,"gustFactor":0.44,"variabilityDeg":69.1,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-transpac': {"fromDeg":39.5,"speedKn":13.1,"gustFactor":0.36,"variabilityDeg":36.7,"source":"open-meteo","sampledAt":"2026-07-01"},
  'race-tri-state': {"fromDeg":74.7,"speedKn":10.5,"gustFactor":0.45,"variabilityDeg":70,"source":"open-meteo","sampledAt":"2026-07-04"},
};
